---
title: "OSCoffee example"
author: "Jeffrey Durieux, MSc"
date: "3/16/2021"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Overview

- iris data
- fuzzy c-means plot
- 

## Iris data

![1. <https://commons.wikimedia.org/w/index.php?curid=9805580>\
2. <https://commons.wikimedia.org/w/index.php?curid=248095>\
3. <https://commons.wikimedia.org/w/index.php?curid=170298>\
](flowerpics/flowerspics.png)

## Plot

```{r plot, warning=FALSE, message=FALSE}
suppressPackageStartupMessages(library(e1071))
suppressPackageStartupMessages(library(plotly))
df <- iris

# play around with m to change the fuzziness/softness of the clustering
# hard partitioning --> 1.1, soft clustering --> pick a higher number e.g., 2

cm <- cmeans(x = df[,-5], centers = 3, m = 2)
suppressPackageStartupMessages(library(plotly))
dff <- data.frame(iris[,-5], lab = as.factor( cm$cluster), 
                  fuzzy = round(apply(cm$membership, MARGIN = 1, max),3))

dff %>% plot_ly(x=~Sepal.Length,y=~Sepal.Width, color = ~lab, text = ~fuzzy)
```


## Pie chart 
```{r pie}
plot_ly(dff, labels = ~lab,type = 'pie')
```

## Conclusion

You can make ppt presentations with R Markdown
